name: satvid
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.16.3
  - matplotlib=3.0.3
  - pillow=6.2.1
  - earthengine-api=0.1.236
  - gdal=2.3.3
  - pandas=0.24.2
  - geopandas=0.4.1
  - pytz=2020.1
  - scikit-image
  - scikit-learn
  - shapely=1.6.4
  - scipy=1.2.1
  - astropy=3.2.1
  - pyqt
  - notebook
  - pip: 
    - opencv-python
